import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getAllTickers } from '../utils/tickers';

export async function getStaticProps() {
  const allTickers = await getAllTickers();
  return {
    props: {
      allTickers,
    },
  };
}


export default function Home({ allTickers }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Dio <a href="https://github.com/PalmeseMattia">Cane</a>
        </h1>
        <ul>
        {allTickers.map(tick =>(
          <li>{tick.name}</li>
        ))}
        </ul>
      </main>
    </div>
        
  )
}
